openapi: 3.0.0
info:
  title: Averroes Taks APIs docs
  version: 0.1.0
servers:
  - url: 'http://localhost:8080'
paths:
  /status:
    get:
      summary: Returns if the server is healthy or not
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string